name: Update Daily Pollution Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run the data fetching script
        run: python fetch_data.py
        env:
          DATA_GOV_API_KEY: ${{ secrets.DATA_GOV_API_KEY }}

      - name: Commit and push the updated data
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add pollution_data.csv # <-- REVERTED TO THE CSV FILE
          git commit -m "Automated daily data update" || exit 0
          git push